version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/app/nginx.tmpl

  socketio:
    build:
      context: .
    image: broadcast_back_end_socketio
    environment:
      - VIRTUAL_HOST=socketio.local
      - USE_IP_HASH=1
      - IP_HASH=1
    depends_on:
      - redis
    command: ["make", "run"]

  redis:
    image: redis:5.0
    container_name: websocket.redis
