version: "3"

services:
  socketio:
    build:
      context: .
    image: broadcast_back_end_socketio
    container_name: websocket.socketio
    depends_on:
      - redis
    ports:
      - "8200:8200"
    command: ["make", "run"]
    sysctls:
      - net.core.somaxconn=8192
      - net.ipv4.tcp_syncookies=0
      - net.ipv4.tcp_max_syn_backlog=2048
      # - net.ipv4.tcp_abort_on_overflow=1

  redis:
    image: redis:5.0
    container_name: websocket.redis
